name: Deploy Backend to VPS

on:
  push:
    branches:
      - integrazione

jobs:
  deploy:
    name: Deploy BE
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Rebuild backend container
        run: |
          cd /opt/stacks/sito-banda
          docker compose up --build -d backend
          echo "✅ BE Deploy completato"
