name: Deploy Backend to VPS

on:
  push:
    branches:
      - integrazione

jobs:
  deploy:
    name: Deploy BE
    runs-on: self-hosted

    steps:
      - name: Pull latest code and rebuild backend
        run: |
          cd /opt/stacks/sito-banda/sito-presentazione-banda-be-new
          git pull origin integrazione
          cd /opt/stacks/sito-banda
          docker compose up --build -d backend
          echo "✅ BE Deploy completato"
